import {
  printUnaryOperationTests,
  printBinaryOperationTests,
  printDivModTests,
  printPowerTests,
  printShiftOperationTests
} from './printing_functions';

console.log(`\
// So you made a mistake of opening this file...
// Ehh...

import XCTest
@testable import BigInt

/// Tests generated by Node.js.
/// See 'Scripts/bigint_generate_node_tests' for details.
///
/// We could have used some other bigint library (for example GMP),
/// but this is a bit easier to manage.
class NodeTests: XCTestCase {
`);

printUnaryOperationTests('Plus', (a) => a);
printUnaryOperationTests('Minus', (a) => -a);
printUnaryOperationTests('Invert', (a) => ~a);

printBinaryOperationTests('Add', (a, b) => a + b);
printBinaryOperationTests('Sub', (a, b) => a - b);
printBinaryOperationTests('Mul', (a, b) => a * b);
printBinaryOperationTests('Div', (a, b) => a / b);
printBinaryOperationTests('Mod', (a, b) => a % b);

printDivModTests();
printPowerTests();

printBinaryOperationTests('And', (a, b) => a & b);
printBinaryOperationTests('Or', (a, b) => a | b);
printBinaryOperationTests('Xor', (a, b) => a ^ b);

printShiftOperationTests('Left', (a, b) => a << b);
printShiftOperationTests('Right', (a, b) => a >> b);

console.log('}');
